# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1248426864);
user_pref("app.update.lastUpdateTime.background-update-timer", 1248426863);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1248426863);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1248426863);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1248426880);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1248426864);
user_pref("browser.backspace_action", 0);
user_pref("browser.download.lastDir", "/root/Downloads");
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://egzamin:8080/dystrybucja/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.1");
user_pref("browser.startup.page", 0);
user_pref("extensions.enabledItems", "{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}:0.8.1,chromifox@altmusictv.com:1.1.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.1");
user_pref("extensions.lastAppVersion", "3.5.1");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("font.name.serif.x-western", "DejaVu Sans");
user_pref("font.size.variable.x-western", 14);
user_pref("general.skins.selectedSkin", "Chromifox");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.app.slik", "/usr/bin/kactivate");
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.warn_viewing_mixed", false);
user_pref("spellchecker.dictionary", "en-US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1293651320);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
